sudo: required
services:
  - docker
before_install:
  - docker pull surendrajat/twrp-builder:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-5.1.1-cleaned/omni_twrp-5.1.1_cleaned.tar.xz
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/TwrpBuilder/android_device_samsung_a6ltexx.git device/samsung/a6ltexx
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /root/twrp/
    source build/envsetup.sh && lunch omni_a6ltexx-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/a6ltexx/recovery.img $HOME/twrp/TWRP-$version-a6ltexx-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: TwrpBuilder/android_device_samsung_a6ltexx
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
